server {
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/freeqr.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/freeqr.xyz/privkey.pem;
    server_name freeqr.xyz;
    root /Users/francip/src/freeqr/dist;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
